
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${ECR_REPO_URI:-calendar-insights}:latest
    environment:
      - SQLITE_DB_PATH=/data/sqlite/meetings.db
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-west-2}
    volumes:
      - ../data/sqlite:/data/sqlite
    network_mode: "host"
    ports:
      - "127.0.0.1:8501:8501"

volumes:
  efs-sqlite:
    driver: local
