# GitLab Secret Detection Ruleset
# This file customizes the secret detection rules for this project

[secrets]
# Disable password in URL detection for specific documentation files
[[secrets.passthrough]]
  type = "file"
  target = "app-gcp/LOCAL_DEVELOPMENT.md"

# Disable password in URL detection for template files  
[[secrets.passthrough]]
  type = "file"
  target = "app-gcp/credentials/service-account.template.json"

# Disable password in URL detection for configuration files
[[secrets.passthrough]]
  type = "file"
  target = ".gitlab-ci.yml"

# Disable password in URL detection for shell scripts that use environment variables
[[secrets.passthrough]]
  type = "file"
  target = "app-gcp/setup-dev.sh"
