# GitLab Secret Detection Ruleset
# This file customizes the secret detection rules for this project

[secrets]
# Disable password in URL detection for template files  
[[secrets.passthrough]]
  type = "file"
  target = "app-gcp/credentials/service-account.template.json"

# Disable password in URL detection for configuration files
[[secrets.passthrough]]
  type = "file"
  target = ".gitlab-ci.yml"

# Disable password in URL detection for example files
[[secrets.passthrough]]
  type = "file"
  target = "app-gcp/env.local.example"

# Disable password in URL detection for template files
[[secrets.passthrough]]
  type = "file"
  target = "app-gcp/env.template"
